### ISSUE TITLE
tac is not portable

### ISSUE THREAD

**Issue by somatoko** [ouest/asdf-perl#12]
Hi,

If I invoke `asdf list all perl` command on osx I get following

```
No compatible versions available (perl )
```

Inside `bin/list-all` I see the following line
```
$(perl_install_bin) --list-all | tac | tr '\n' ' '
```

According to this [answer](https://stackoverflow.com/a/742485) `tac` can
be replaced by `tail -r` command.

Can you please adjust it.

**Comment by ouest** [comment]
@somatoko 
Sorry for the delay.
I have corrected it below.
Can you please check if it works?
https://github.com/ouest/asdf-perl/pull/13
